distribution_code_name: "ibus-rime"
distribution_name: Rime
distribution_version: 1.5.0
install_time: "Sun Nov 14 16:14:45 2021"
installation_id: "e778cdc0-6bca-4148-ae83-6766ddb9099d"
rime_version: 1.7.2
update_time: "Sun Mar  6 08:33:35 2022"