distribution_code_name: "ibus-rime"
distribution_name: Rime
distribution_version: 1.5.0
install_time: "Sun Mar 13 16:00:23 2022"
installation_id: "salt-linux"
rime_version: 1.7.3
sync_dir: "WorkSpace/dotfiles/config/rime/sync"
update_time: "Mon Jun  6 11:42:01 2022"