var:
  last_build_time: 1659862200
  option:
    simplification: true
  previously_selected_schema: double_pinyin
  schema_access_time:
    double_pinyin: 1659860501
    double_pinyin_flypy: 1659858942
    luna_pinyin: 1659859907