var:
  last_build_time: 1659708461
  option:
    full_shape: false
    simplification: true
  previously_selected_schema: double_pinyin
  schema_access_time:
    double_pinyin: 1655723661
    wubi_pinyin: 1655712335