var:
  last_build_time: 1649334080
  option:
    full_shape: false
    simplification: true
  previously_selected_schema: double_pinyin
  schema_access_time:
    bopomofo: 1647565204
    cangjie5: 1647565238
    double_pinyin: 1649071043
    double_pinyin_flypy: 1647698876
    emoji: 1647699825
    luna_pinyin: 1649071012
    pinyin_simp: 1649071036
    wubi_pinyin: 1648624803