var:
  last_build_time: 1638322178
  option:
    simplification: true
  previously_selected_schema: double_pinyin
  schema_access_time:
    cangjie5: 1637934642
    double_pinyin: 1638709032
    emoji: 1637725316
    wubi86: 1638708991
    wubi_pinyin: 1638172885