__patch:
# Rx: emoji:customize:schema=double_pinyin {
  - patch/+:
      __include: emoji_suggestion:/patch
# }
# Rx: BlindingDark/rime-easy-en:customize:schema=double_pinyin {
  - patch/+:
      __include: easy_en:/patch
# }
