distribution_code_name: "ibus-rime"
distribution_name: Rime
distribution_version: 1.5.0
install_time: "Sun Mar 13 16:00:23 2022"
installation_id: "sync-rime"
rime_version: 1.8.4
update_time: "Sun Apr 23 16:39:17 2023"